language: node_js
node_js:
  - "node"
script:
    - yarn run lint
    - yarn run test
    - yarn run coverage
notifications:
    slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: ed12a3d8fc8d0024c18acfefa66d55ae1c11298d8f5ccfc3a10006d9a37c02df
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
