sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules
language: node_js
services: 
  - docker
node_js:
  - "node"
script:
    - npm run lint
    - npm run test
    - npm run coverage
    - npm run build
notifications:
    slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: ed12a3d8fc8d0024c18acfefa66d55ae1c11298d8f5ccfc3a10006d9a37c02df
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
  - openssl aes-256-cbc -K $encrypted_0d5a066bcda1_key -iv $encrypted_0d5a066bcda1_iv -in client-secret.json.enc -out client-secret.json -d;
  - ./deployToGCS.sh challenge_of_the_day
